import time
from re import S
from framework.basic_fiber import FiberTest
from test_cases.fiber.devnet.settle_invoice.test_settle_invoice import sha256_hex


def _wait_all_payments_success(payment_groups, timeout=120):
    pending = [
        (fiber, payment_hash)
        for fiber, payment_hashes in payment_groups
        for payment_hash in payment_hashes
    ]
    deadline = time.monotonic() + timeout
    last_states = {}
    while pending and time.monotonic() < deadline:
        still_pending = []
        for fiber, payment_hash in pending:
            client = fiber.get_client()
            rpc_url = client.url
            payment = client.get_payment({"payment_hash": payment_hash})
            last_states[(rpc_url, payment_hash)] = payment["status"]
            if payment["status"] == "Failed":
                assert False, f"payment failed on {rpc_url}: {payment}"
            if payment["status"] != "Success":
                still_pending.append((fiber, payment_hash))
        pending = still_pending
        if pending:
            time.sleep(1)
    remaining = [
        {
            "rpc_url": fiber.get_client().url,
            "payment_hash": payment_hash,
            "status": last_states.get((fiber.get_client().url, payment_hash)),
        }
        for fiber, payment_hash in pending
    ]
    assert not pending, f"payments timed out after {timeout}s: {remaining}"


class BatchSettle(FiberTest):

    def test_batch_settle(self):
        """
        new invoice N 个tlc
        同时调用settle N 个tlc
        Returns:
        """
        self.fiber3 = self.start_new_fiber(self.generate_account(10000))
        # self.fiber3 = self.start_new_mock_fiber("")
        for i in range(3):
            self.open_channel(
                self.fiber1, self.fiber2, 1000 * 100000000, 1000 * 100000000
            )
            self.open_channel(
                self.fiber2, self.fiber3, 1000 * 100000000, 1000 * 100000000
            )
        for j in range(1):
            before_balances = self.get_fibers_balance()
            fiber1_invoice_size = 60
            fiber1_invoices = []
            fiber1_preimages = []
            fiber1_invoice_hashes = []
            fiber3_sent_payment_hashes = []
            for i in range(fiber1_invoice_size):
                preimage = self.generate_random_preimage()
                invoice_hash = sha256_hex(preimage)
                invoice = self.fiber1.get_client().new_invoice(
                    {
                        "amount": hex(1 * 100000000),
                        "currency": "Fibd",
                        "description": "test invoice generated by node2",
                        "payment_hash": invoice_hash,
                        "hash_algorithm": "sha256",
                        "allow_mpp": False,
                    }
                )
                fiber1_invoices.append(invoice)
                fiber1_preimages.append(preimage)
                fiber1_invoice_hashes.append(invoice_hash)

            fiber3_invoice_size = 60
            fiber3_invoices = []
            fiber3_preimages = []
            fiber3_invoice_hashes = []
            fiber1_sent_payment_hashes = []
            for i in range(fiber3_invoice_size):
                preimage = self.generate_random_preimage()
                invoice_hash = sha256_hex(preimage)
                invoice = self.fiber3.get_client().new_invoice(
                    {
                        "amount": hex(1 * 100000000),
                        "currency": "Fibd",
                        "description": "test invoice generated by node2",
                        "payment_hash": invoice_hash,
                        "hash_algorithm": "sha256",
                        "allow_mpp": False,
                    }
                )
                fiber3_invoices.append(invoice)
                fiber3_preimages.append(preimage)
                fiber3_invoice_hashes.append(invoice_hash)
            # fiber3 -> fiber1
            for invoice in fiber1_invoices:
                payment = self.fiber3.get_client().send_payment(
                    {
                        "invoice": invoice["invoice_address"],
                    }
                )
                fiber3_sent_payment_hashes.append(payment["payment_hash"])

            # fiber1 -> fiber3
            for invoice in fiber3_invoices:
                payment = self.fiber1.get_client().send_payment(
                    {
                        "invoice": invoice["invoice_address"],
                    }
                )
                fiber1_sent_payment_hashes.append(payment["payment_hash"])

            # wait all invoice ture receive
            for invoice in fiber3_invoices:
                self.wait_invoice_state(
                    self.fiber3, invoice["invoice"]["data"]["payment_hash"], "Received"
                )

            for invoice in fiber1_invoices:
                self.wait_invoice_state(
                    self.fiber1, invoice["invoice"]["data"]["payment_hash"], "Received"
                )

            # settle invoice same time
            for i in range(len(fiber1_invoices)):
                self.fiber1.get_client().settle_invoice(
                    {
                        "payment_hash": fiber1_invoice_hashes[i],
                        "payment_preimage": fiber1_preimages[i],
                    }
                )

            for i in range(len(fiber3_invoices)):
                self.fiber3.get_client().settle_invoice(
                    {
                        "payment_hash": fiber3_invoice_hashes[i],
                        "payment_preimage": fiber3_preimages[i],
                    }
                )

            for invoice in fiber1_invoices:
                self.wait_invoice_state(
                    self.fiber1, invoice["invoice"]["data"]["payment_hash"], "Paid"
                )

            for invoice in fiber3_invoices:
                self.wait_invoice_state(
                    self.fiber3, invoice["invoice"]["data"]["payment_hash"], "Paid"
                )

            _wait_all_payments_success(
                (
                    (self.fiber3, fiber3_sent_payment_hashes),
                    (self.fiber1, fiber1_sent_payment_hashes),
                )
            )

            time.sleep(10)
            after_balances = self.get_fibers_balance()
            print(
                "[0]a-b:",
                before_balances[0]["ckb"]["local_balance"]
                - after_balances[0]["ckb"]["local_balance"],
            )
            assert (
                before_balances[0]["ckb"]["local_balance"]
                - after_balances[0]["ckb"]["local_balance"]
                == 6000000
            )
            print(
                "[0]a-b:",
                before_balances[0]["ckb"]["offered_tlc_balance"]
                - after_balances[0]["ckb"]["offered_tlc_balance"],
            )
            assert before_balances[0]["ckb"]["offered_tlc_balance"] == 0
            assert after_balances[0]["ckb"]["offered_tlc_balance"] == 0
            print(
                "[0]a-b:",
                before_balances[0]["ckb"]["received_tlc_balance"]
                - after_balances[0]["ckb"]["received_tlc_balance"],
            )
            assert before_balances[0]["ckb"]["received_tlc_balance"] == 0
            assert after_balances[0]["ckb"]["received_tlc_balance"] == 0

            print(
                "[1]a-b:",
                before_balances[1]["ckb"]["local_balance"]
                - after_balances[1]["ckb"]["local_balance"],
            )
            assert (
                before_balances[1]["ckb"]["local_balance"]
                - after_balances[1]["ckb"]["local_balance"]
                == -12000000
            )

            print(
                "[1]a-b:",
                before_balances[1]["ckb"]["offered_tlc_balance"]
                - after_balances[1]["ckb"]["offered_tlc_balance"],
            )
            assert before_balances[1]["ckb"]["offered_tlc_balance"] == 0
            assert after_balances[1]["ckb"]["offered_tlc_balance"] == 0

            print(
                "[1]a-b:",
                before_balances[1]["ckb"]["received_tlc_balance"]
                - after_balances[1]["ckb"]["received_tlc_balance"],
            )
            assert before_balances[1]["ckb"]["received_tlc_balance"] == 0
            assert after_balances[1]["ckb"]["received_tlc_balance"] == 0

            print(
                "[2]a-b:",
                before_balances[2]["ckb"]["local_balance"]
                - after_balances[2]["ckb"]["local_balance"],
            )
            assert (
                before_balances[2]["ckb"]["local_balance"]
                - after_balances[2]["ckb"]["local_balance"]
                == 6000000
            )

            print(
                "[2]a-b:",
                before_balances[2]["ckb"]["offered_tlc_balance"]
                - after_balances[2]["ckb"]["offered_tlc_balance"],
            )
            assert before_balances[2]["ckb"]["offered_tlc_balance"] == 0
            assert after_balances[2]["ckb"]["offered_tlc_balance"] == 0
            print(
                "[2]a-b:",
                before_balances[2]["ckb"]["received_tlc_balance"]
                - after_balances[2]["ckb"]["received_tlc_balance"],
            )
            assert before_balances[2]["ckb"]["received_tlc_balance"] == 0
            assert after_balances[2]["ckb"]["received_tlc_balance"] == 0

            fiber1_peers = {
                peer["pubkey"]
                for peer in self.fiber1.get_client().list_peers()["peers"]
            }
            fiber2_peers = {
                peer["pubkey"]
                for peer in self.fiber2.get_client().list_peers()["peers"]
            }
            fiber3_peers = {
                peer["pubkey"]
                for peer in self.fiber3.get_client().list_peers()["peers"]
            }
            assert self.fiber2.get_pubkey() in fiber1_peers
            assert {
                self.fiber1.get_pubkey(),
                self.fiber3.get_pubkey(),
            } <= fiber2_peers
            assert self.fiber2.get_pubkey() in fiber3_peers

            final_payment_hash = self.send_payment(
                self.fiber1, self.fiber3, 1 * 100000000
            )
            assert (
                self.fiber1.get_client().get_payment(
                    {"payment_hash": final_payment_hash}
                )["status"]
                == "Success"
            )
            reverse_payment_hash = self.send_payment(
                self.fiber3, self.fiber1, 1 * 100000000
            )
            assert (
                self.fiber3.get_client().get_payment(
                    {"payment_hash": reverse_payment_hash}
                )["status"]
                == "Success"
            )
